remote: true

experienceLevel:
  internship: true
  entry: true
  associate: true
  mid-senior level: false
  director: false
  executive: false

jobTypes:
  full-time: true
  contract: false
  part-time: false
  temporary: false
  internship: true
  other: false
  volunteer: true

date:
  all time: true
  month: true
  week: true
  24 hours: true

positions:
  - Software engineer
  - Software developer
  - Full stack developer
  - Front end developer
  - Java developer
  - Web developer

locations:
  - India
  



apply_once_at_company: true

distance: 100

company_blacklist:
 
  - Crossover

title_blacklist:
  - word1
  - word2

location_blacklist:
  - Brazil

job_applicants_threshold:
  min_applicants: 0
  max_applicants: 30

# llm_model_type: openai
# llm_model: 'gpt-4o-mini'
# llm_api_url: 'https://api.pawan.krd/cosmosrp/v1'

llm_model_type: gemini
llm_model: 'gemini-1.0-pro'
llm_api_url: 'https://aistudio.google.com/app/apikey'